trigger:
  - main

variables:
  buildConfiguration: 'Release'

jobs:

- job: BuildAndDeployBackend
  displayName: 'Build & Deploy .NET API'
  pool:
    vmImage: 'windows-latest'
  steps:

  - task: UseDotNet@2
    displayName: 'Setup .NET 8'
    inputs:
      version: '8.0.x'
      packageType: 'sdk'

  - task: DotNetCoreCLI@2
    displayName: 'Restore packages'
    inputs:
      command: 'restore'
      projects: 'WMS-Solution.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: 'WMS-Solution.sln'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: 'WMS.Tests/WMS.Tests.csproj'
    continueOnError: true

  - task: DotNetCoreCLI@2
    displayName: 'Publish API'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'WMS.API/WMS.API.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Backend Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
      ArtifactName: 'backend'

  - task: AzureWebApp@1
    displayName: 'Deploy API to App Service'
    inputs:
      azureSubscription: 'WMS-Azure-Connection'
      appType: 'webAppLinux'
      appName: 'wms-api-prod'
      package: '$(Build.ArtifactStagingDirectory)/api/**/*.zip'

- job: BuildAndDeployFrontend
  displayName: 'Build & Deploy Angular'
  pool:
    vmImage: 'windows-latest'
  steps:

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '20.x'

  - script: |
      cd WMS.Frontend
      npm install
    displayName: 'Install npm packages'

  - script: |
      cd WMS.Frontend
      npm run build -- --configuration production
    displayName: 'Build Angular'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Frontend Artifact'
    inputs:
      PathtoPublish: 'WMS.Frontend/dist/wms-frontend/browser'
      ArtifactName: 'frontend'

  - task: AzureWebApp@1
    displayName: 'Deploy Angular to App Service'
    inputs:
      azureSubscription: 'WMS-Azure-Connection'
      appType: 'webAppLinux'
      appName: 'wms-frontend-prod'
      package: 'WMS.Frontend/dist/wms-frontend/browser'